---
title: "Comb_Maps_APP"
author: "JCLAraujo"
date: "21/09/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, "executa os pacotes", message=FALSE, warning=FALSE, echo=FALSE}

require(raster)
require(rgdal)
require(rgeos)

```

```{r, "carrega os mapas", echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

######carrega os mapas necessários
mapa_CAR_BDA<-readOGR(dsn="./DATA_USE/CAR/Barão_de_Antonina",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_BSI<-readOGR(dsn="./DATA_USE/CAR/Bom_Sucesso_de_Itararé",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_BUR<-readOGR(dsn="./DATA_USE/CAR/Buri",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_CAB<-readOGR(dsn="./DATA_USE/CAR/Capão_Bonito",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_COM<-readOGR(dsn="./DATA_USE/CAR/Coronel_Macedo",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_GUA<-readOGR(dsn="./DATA_USE/CAR/Guapiara",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_ITB<-readOGR(dsn="./DATA_USE/CAR/Itaberá",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_ITP<-readOGR(dsn="./DATA_USE/CAR/Itapeva",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_ITO<-readOGR(dsn="./DATA_USE/CAR/Itaporanga",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_ITR<-readOGR(dsn="./DATA_USE/CAR/Itararé",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_NOV<-readOGR(dsn="./DATA_USE/CAR/Nova_Campina",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_RIG<-readOGR(dsn="./DATA_USE/CAR/Ribeirão_Grande",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_RIV<-readOGR(dsn="./DATA_USE/CAR/Riversul",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_TAQ<-readOGR(dsn="./DATA_USE/CAR/Taquarituba",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")
mapa_CAR_TAU<-readOGR(dsn="./DATA_USE/CAR/Taquarivaí",layer="AREA_IMOVEL", use_iconv=TRUE, encoding="UTF-8")

####################################################################################################################################

mapa_mda_BDA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3505005_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_BSI<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3507159_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_BUR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3508009_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_CAB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3510203_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_COM<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3512605_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_GUA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3517604_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_ITB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3521705_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_ITP<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522406_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_ITO<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522802_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_ITR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3523206_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_NOV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3532827_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_RIG<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543253_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_RIV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543501_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_TAQ<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553807_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")
mapa_mda_TAU<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553856_MASSAS_DAGUA", use_iconv=TRUE, encoding="UTF-8")

####################################################################################################################################

mapa_nas_BDA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3505005_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_BSI<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3507159_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_BUR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3508009_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_CAB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3510203_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_COM<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3512605_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_GUA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3517604_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_ITB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3521705_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_ITP<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522406_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_ITO<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522802_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_ITR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3523206_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_NOV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3532827_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_RIG<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543253_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_RIV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543501_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_TAQ<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553807_NASCENTES", use_iconv=TRUE, encoding="UTF-8")
mapa_nas_TAU<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553856_NASCENTES", use_iconv=TRUE, encoding="UTF-8")

####################################################################################################################################

mapa_rms_BDA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3505005_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_BSI<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3507159_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_BUR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3508009_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_CAB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3510203_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_COM<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3512605_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_GUA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3517604_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_ITB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3521705_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_ITP<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522406_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_ITO<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522802_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_ITR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3523206_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_NOV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3532827_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_RIG<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543253_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_RIV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543501_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_TAQ<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553807_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")
mapa_rms_TAU<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553856_RIOS_SIMPLES", use_iconv=TRUE, encoding="UTF-8")

###################################################################################################################################

mapa_rmd_BDA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3505005_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_BUR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3508009_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_CAB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3510203_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_COM<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3512605_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_GUA<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3517604_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_ITB<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3521705_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_ITP<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522406_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_ITO<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3522802_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_ITR<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3523206_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_NOV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3532827_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_RIG<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543253_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_RIV<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3543501_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_TAQ<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553807_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")
mapa_rmd_TAU<-readOGR(dsn="./DATA_USE/FBDS_Hidrografia",layer="SP_3553856_RIOS_DUPLOS", use_iconv=TRUE, encoding="UTF-8")

####################################################################################################################################

mapa_uso_BDA<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3505005_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_BSI<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3507159_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_BUR<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3508009_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_CAB<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3510203_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_COM<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3512605_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_GUA<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3517604_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_ITB<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3521705_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_ITP<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3522406_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_ITO<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3522802_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_ITR<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3523206_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_NOV<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3532827_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_RIG<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3543253_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_RIV<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3543501_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_TAQ<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3553807_USO", use_iconv=TRUE, encoding="UTF-8")
mapa_uso_TAU<-readOGR(dsn="./DATA_USE/FBDS_APP_USO_Municipios",layer="SP_3553856_USO", use_iconv=TRUE, encoding="UTF-8")

###################################################################################################################################

mapa_geo<-readOGR(dsn="./DATA_USE",layer="Geomorf_sudoeste", use_iconv=TRUE, encoding="UTF-8")

```

```{r, "muda a projeção"}
#list_map_proj<-c(mapa_CAR_BDA, mapa_CAR_BSI,mapa_CAR_BUR,mapa_CAR_CAB,mapa_CAR_COM,mapa_CAR_GUA,mapa_CAR_ITB,mapa_CAR_ITO,mapa_CAR_ITP,mapa_CAR_ITR,mapa_CAR_NOV,mapa_CAR_RIG,mapa_CAR_RIV,mapa_CAR_TAQ,mapa_CAR_TAU,mapa_geo,mapa_mda_BDA,mapa_mda_BDA,mapa_mda_BSI,mapa_mda_BUR,mapa_mda_CAB,mapa_mda_COM,mapa_mda_GUA,mapa_mda_ITB,mapa_mda_ITP,mapa_mda_ITO,mapa_mda_ITR,mapa_mda_NOV,mapa_mda_RIG,mapa_mda_RIV,mapa_mda_TAQ,mapa_mda_TAU,mapa_nas_BDA,mapa_nas_BSI,mapa_nas_BUR,mapa_nas_CAB,mapa_nas_COM,mapa_nas_GUA,mapa_nas_ITB,mapa_nas_ITP,mapa_nas_ITO,mapa_nas_ITR,mapa_nas_NOV,mapa_nas_RIG,mapa_nas_RIV,mapa_nas_TAQ,mapa_nas_TAU,mapa_rms_BDA,mapa_rms_BSI,mapa_rms_BUR,mapa_rms_CAB,mapa_rms_COM,mapa_rms_GUA,mapa_rms_ITB,mapa_rms_ITP,mapa_rms_ITO,mapa_rms_ITR,mapa_rms_NOV,mapa_rms_RIG,mapa_rms_RIV,mapa_rms_TAQ,mapa_rms_TAU,mapa_rmd_BDA,mapa_rmd_BUR,mapa_rmd_CAB,mapa_rmd_COM,mapa_rmd_GUA,mapa_rmd_ITB,mapa_rmd_ITP,mapa_rmd_ITO,mapa_rmd_ITR,mapa_rmd_NOV,mapa_rmd_RIG,mapa_rmd_RIV,mapa_rmd_TAQ,mapa_rmd_TAU,mapa_uso_BDA,mapa_uso_BSI,mapa_uso_BUR,mapa_uso_CAB,mapa_uso_COM,mapa_uso_GUA,mapa_uso_ITB,mapa_uso_ITP,mapa_uso_ITO,mapa_uso_ITR,mapa_uso_NOV,mapa_uso_RIG,mapa_uso_RIV,mapa_uso_TAQ,mapa_uso_TAU)

mapa_CAR_BDA<-spTransform(mapa_CAR_BDA, CRS("+init=epsg:31982"))
mapa_CAR_BSI<-spTransform(mapa_CAR_BSI, CRS("+init=epsg:31982"))
mapa_CAR_BUR<-spTransform(mapa_CAR_BUR, CRS("+init=epsg:31982"))
mapa_CAR_CAB<-spTransform(mapa_CAR_CAB, CRS("+init=epsg:31982"))
mapa_CAR_COM<-spTransform(mapa_CAR_COM, CRS("+init=epsg:31982"))
mapa_CAR_GUA<-spTransform(mapa_CAR_GUA, CRS("+init=epsg:31982"))
mapa_CAR_ITB<-spTransform(mapa_CAR_ITB, CRS("+init=epsg:31982"))
mapa_CAR_ITP<-spTransform(mapa_CAR_ITP, CRS("+init=epsg:31982"))
mapa_CAR_ITO<-spTransform(mapa_CAR_ITO, CRS("+init=epsg:31982"))
mapa_CAR_ITR<-spTransform(mapa_CAR_ITR, CRS("+init=epsg:31982"))
mapa_CAR_NOV<-spTransform(mapa_CAR_NOV, CRS("+init=epsg:31982"))
mapa_CAR_RIG<-spTransform(mapa_CAR_RIG, CRS("+init=epsg:31982"))
mapa_CAR_RIV<-spTransform(mapa_CAR_RIV, CRS("+init=epsg:31982"))
mapa_CAR_TAQ<-spTransform(mapa_CAR_TAQ, CRS("+init=epsg:31982"))
mapa_CAR_TAU<-spTransform(mapa_CAR_TAU, CRS("+init=epsg:31982"))

####################################################################################################################################

mapa_mda_BDA<-spTransform(mapa_mda_BDA, CRS("+init=epsg:31982"))
mapa_mda_BSI<-spTransform(mapa_mda_BSI, CRS("+init=epsg:31982"))
mapa_mda_BUR<-spTransform(mapa_mda_BUR, CRS("+init=epsg:31982"))
mapa_mda_CAB<-spTransform(mapa_mda_CAB, CRS("+init=epsg:31982"))
mapa_mda_COM<-spTransform(mapa_mda_COM, CRS("+init=epsg:31982"))
mapa_mda_GUA<-spTransform(mapa_mda_GUA, CRS("+init=epsg:31982"))
mapa_mda_ITB<-spTransform(mapa_mda_ITB, CRS("+init=epsg:31982"))
mapa_mda_ITP<-spTransform(mapa_mda_ITP, CRS("+init=epsg:31982"))
mapa_mda_ITO<-spTransform(mapa_mda_ITO, CRS("+init=epsg:31982"))
mapa_mda_ITR<-spTransform(mapa_mda_ITR, CRS("+init=epsg:31982"))
mapa_mda_NOV<-spTransform(mapa_mda_NOV, CRS("+init=epsg:31982"))
mapa_mda_RIG<-spTransform(mapa_mda_RIG, CRS("+init=epsg:31982"))
mapa_mda_RIV<-spTransform(mapa_mda_RIV, CRS("+init=epsg:31982"))
mapa_mda_TAQ<-spTransform(mapa_mda_TAQ, CRS("+init=epsg:31982"))
mapa_mda_TAU<-spTransform(mapa_mda_TAU, CRS("+init=epsg:31982"))

####################################################################################################################################

mapa_nas_BDA<-spTransform(mapa_nas_BDA, CRS("+init=epsg:31982"))
mapa_nas_BSI<-spTransform(mapa_nas_BSI, CRS("+init=epsg:31982"))
mapa_nas_BUR<-spTransform(mapa_nas_BUR, CRS("+init=epsg:31982"))
mapa_nas_CAB<-spTransform(mapa_nas_CAB, CRS("+init=epsg:31982"))
mapa_nas_COM<-spTransform(mapa_nas_COM, CRS("+init=epsg:31982"))
mapa_nas_GUA<-spTransform(mapa_nas_GUA, CRS("+init=epsg:31982"))
mapa_nas_ITB<-spTransform(mapa_nas_ITB, CRS("+init=epsg:31982"))
mapa_nas_ITP<-spTransform(mapa_nas_ITP, CRS("+init=epsg:31982"))
mapa_nas_ITO<-spTransform(mapa_nas_ITO, CRS("+init=epsg:31982"))
mapa_nas_ITR<-spTransform(mapa_nas_ITR, CRS("+init=epsg:31982"))
mapa_nas_NOV<-spTransform(mapa_nas_NOV, CRS("+init=epsg:31982"))
mapa_nas_RIG<-spTransform(mapa_nas_RIG, CRS("+init=epsg:31982"))
mapa_nas_RIV<-spTransform(mapa_nas_RIV, CRS("+init=epsg:31982"))
mapa_nas_TAQ<-spTransform(mapa_nas_TAQ, CRS("+init=epsg:31982"))
mapa_nas_TAU<-spTransform(mapa_nas_TAU, CRS("+init=epsg:31982"))

####################################################################################################################################

mapa_rms_BDA<-spTransform(mapa_rms_BDA, CRS("+init=epsg:31982"))
mapa_rms_BSI<-spTransform(mapa_rms_BSI, CRS("+init=epsg:31982"))
mapa_rms_BUR<-spTransform(mapa_rms_BUR, CRS("+init=epsg:31982"))
mapa_rms_CAB<-spTransform(mapa_rms_CAB, CRS("+init=epsg:31982"))
mapa_rms_COM<-spTransform(mapa_rms_COM, CRS("+init=epsg:31982"))
mapa_rms_GUA<-spTransform(mapa_rms_GUA, CRS("+init=epsg:31982"))
mapa_rms_ITB<-spTransform(mapa_rms_ITB, CRS("+init=epsg:31982"))
mapa_rms_ITP<-spTransform(mapa_rms_ITP, CRS("+init=epsg:31982"))
mapa_rms_ITO<-spTransform(mapa_rms_ITO, CRS("+init=epsg:31982"))
mapa_rms_ITR<-spTransform(mapa_rms_ITR, CRS("+init=epsg:31982"))
mapa_rms_NOV<-spTransform(mapa_rms_NOV, CRS("+init=epsg:31982"))
mapa_rms_RIG<-spTransform(mapa_rms_RIG, CRS("+init=epsg:31982"))
mapa_rms_RIV<-spTransform(mapa_rms_RIV, CRS("+init=epsg:31982"))
mapa_rms_TAQ<-spTransform(mapa_rms_TAQ, CRS("+init=epsg:31982"))
mapa_rms_TAU<-spTransform(mapa_rms_TAU, CRS("+init=epsg:31982"))

###################################################################################################################################

mapa_rmd_BDA<-spTransform(mapa_rmd_BDA, CRS("+init=epsg:31982"))
mapa_rmd_BSI<-spTransform(mapa_rmd_BSI, CRS("+init=epsg:31982"))
mapa_rmd_BUR<-spTransform(mapa_rmd_BUR, CRS("+init=epsg:31982"))
mapa_rmd_CAB<-spTransform(mapa_rmd_CAB, CRS("+init=epsg:31982"))
mapa_rmd_COM<-spTransform(mapa_rmd_COM, CRS("+init=epsg:31982"))
mapa_rmd_GUA<-spTransform(mapa_rmd_GUA, CRS("+init=epsg:31982"))
mapa_rmd_ITB<-spTransform(mapa_rmd_ITB, CRS("+init=epsg:31982"))
mapa_rmd_ITP<-spTransform(mapa_rmd_ITP, CRS("+init=epsg:31982"))
mapa_rmd_ITO<-spTransform(mapa_rmd_ITO, CRS("+init=epsg:31982"))
mapa_rmd_ITR<-spTransform(mapa_rmd_ITR, CRS("+init=epsg:31982"))
mapa_rmd_NOV<-spTransform(mapa_rmd_NOV, CRS("+init=epsg:31982"))
mapa_rmd_RIG<-spTransform(mapa_rmd_RIG, CRS("+init=epsg:31982"))
mapa_rmd_RIV<-spTransform(mapa_rmd_RIV, CRS("+init=epsg:31982"))
mapa_rmd_TAQ<-spTransform(mapa_rmd_TAQ, CRS("+init=epsg:31982"))
mapa_rmd_TAU<-spTransform(mapa_rmd_TAU, CRS("+init=epsg:31982"))

####################################################################################################################################

mapa_uso_BDA<-spTransform(mapa_uso_BDA, CRS("+init=epsg:31982"))
mapa_uso_BSI<-spTransform(mapa_uso_BSI, CRS("+init=epsg:31982"))
mapa_uso_BUR<-spTransform(mapa_uso_BUR, CRS("+init=epsg:31982"))
mapa_uso_CAB<-spTransform(mapa_uso_CAB, CRS("+init=epsg:31982"))
mapa_uso_COM<-spTransform(mapa_uso_COM, CRS("+init=epsg:31982"))
mapa_uso_GUA<-spTransform(mapa_uso_GUA, CRS("+init=epsg:31982"))
mapa_uso_ITB<-spTransform(mapa_uso_ITB, CRS("+init=epsg:31982"))
mapa_uso_ITP<-spTransform(mapa_uso_ITP, CRS("+init=epsg:31982"))
mapa_uso_ITO<-spTransform(mapa_uso_ITO, CRS("+init=epsg:31982"))
mapa_uso_ITR<-spTransform(mapa_uso_ITR, CRS("+init=epsg:31982"))
mapa_uso_NOV<-spTransform(mapa_uso_NOV, CRS("+init=epsg:31982"))
mapa_uso_RIG<-spTransform(mapa_uso_RIG, CRS("+init=epsg:31982"))
mapa_uso_RIV<-spTransform(mapa_uso_RIV, CRS("+init=epsg:31982"))
mapa_uso_TAQ<-spTransform(mapa_uso_TAQ, CRS("+init=epsg:31982"))
mapa_uso_TAU<-spTransform(mapa_uso_TAU, CRS("+init=epsg:31982"))

###################################################################################################################################

mapa_geo<-spTransform(mapa_geo, CRS("+init=epsg:31982"))
```

```{r, "grupo 1 (Barão de Antonina, Itaporanga, Riversul, Itararé, Bom Sucesso de Itararé)"}
GI_map_uso<-rbind(mapa_uso_BDA, mapa_uso_ITO)
GI_map_uso<-rbind(GI_map_uso, mapa_uso_RIV)
GI_map_uso<-rbind(GI_map_uso, mapa_uso_ITR)
GI_map_uso<-rbind(GI_map_uso, mapa_uso_BSI)

GI_map_mda<-rbind(mapa_mda_BDA, mapa_mda_ITO)
GI_map_mda<-rbind(GI_map_mda, mapa_mda_RIV)
GI_map_mda<-GI_map_mda[,-10, drop=FALSE]
GI_map_mda<-rbind(GI_map_mda, mapa_mda_ITR)
mapa_mda_BSI<-mapa_mda_BSI[,-(9:10), drop=FALSE]
GI_map_mda<-rbind(GI_map_mda, mapa_mda_BSI)

GI_map_nas<-rbind(mapa_nas_BDA, mapa_nas_ITO)
GI_map_nas<-rbind(GI_map_nas, mapa_nas_RIV)
GI_map_nas<-rbind(GI_map_nas, mapa_nas_ITR)
GI_map_nas<-rbind(GI_map_nas, mapa_nas_BSI)

GI_map_rms<-rbind(mapa_rms_BDA, mapa_rms_ITO)
GI_map_rms<-rbind(GI_map_rms, mapa_rms_RIV)
GI_map_rms<-rbind(GI_map_rms, mapa_rms_ITR)
GI_map_rms<-rbind(GI_map_rms, mapa_rms_BSI)

GI_map_rmd<-rbind(mapa_rmd_BDA, mapa_rmd_ITO)
GI_map_rmd<-rbind(GI_map_rmd, mapa_rmd_RIV)
GI_map_rmd<-rbind(GI_map_rmd, mapa_rmd_ITR)

GI_map_CAR<-rbind(mapa_CAR_BDA, mapa_CAR_ITO)
GI_map_CAR<-rbind(GI_map_CAR, mapa_CAR_RIV)
GI_map_CAR<-rbind(GI_map_CAR, mapa_CAR_ITR)
GI_map_CAR<-rbind(GI_map_CAR, mapa_CAR_BSI)
```

```{r, "grupo 2 (Taquarituba, Coronel Macedo, itaberá)"}
GII_map_uso<-rbind(mapa_uso_TAQ, mapa_uso_COM)
GII_map_uso<-rbind(GII_map_uso, mapa_uso_ITB)

GII_map_mda<-rbind(mapa_mda_TAQ, mapa_mda_COM)
GII_map_mda<-rbind(GII_map_mda, mapa_mda_ITB)

GII_map_nas<-rbind(mapa_nas_TAQ, mapa_nas_COM)
GII_map_nas<-rbind(GII_map_nas, mapa_nas_ITB)

GII_map_rms<-rbind(mapa_rms_TAQ, mapa_rms_COM)
GII_map_rms<-rbind(GII_map_rms, mapa_rms_ITB)

GII_map_rmd<-rbind(mapa_rmd_TAQ, mapa_rmd_COM)
GII_map_rmd<-rbind(GII_map_rmd, mapa_rmd_ITB)

GII_map_CAR<-rbind(mapa_CAR_TAQ, mapa_CAR_COM)
GII_map_CAR<-rbind(GII_map_CAR, mapa_CAR_ITB)
```

```{r, "grupo 3 (Itapeva, Nova Campina, Taquarivaí, Guapiara)"}
GIII_map_uso<-rbind(mapa_uso_ITP, mapa_uso_NOV)
GIII_map_uso<-rbind(GIII_map_uso, mapa_uso_TAU)
GIII_map_uso<-rbind(GIII_map_uso, mapa_uso_GUA)

mapa_mda_ITP<-mapa_mda_ITP[, -10, drop=FALSE]
GIII_map_mda<-rbind(mapa_mda_ITP, mapa_mda_NOV)
mapa_mda_TAU<-mapa_mda_TAU[, -10, drop=FALSE]
GIII_map_mda<-rbind(GIII_map_mda, mapa_mda_TAU)
GIII_map_mda<-rbind(GIII_map_mda, mapa_mda_GUA)

GIII_map_nas<-rbind(mapa_nas_ITP, mapa_nas_NOV)
GIII_map_nas<-rbind(GIII_map_nas, mapa_nas_TAU)
GIII_map_nas<-rbind(GIII_map_nas, mapa_nas_GUA)

GIII_map_rms<-rbind(mapa_rms_ITP, mapa_rms_NOV)
GIII_map_rms<-rbind(GIII_map_rms, mapa_rms_TAU)
GIII_map_rms<-rbind(GIII_map_rms, mapa_rms_GUA)

GIII_map_rmd<-rbind(mapa_rmd_ITP, mapa_rmd_NOV)
GIII_map_rmd<-rbind(GIII_map_rmd, mapa_rmd_TAU)
GIII_map_rmd<-rbind(GIII_map_rmd, mapa_rmd_GUA)

GIII_map_CAR<-rbind(mapa_CAR_ITP, mapa_CAR_NOV)
GIII_map_CAR<-rbind(GIII_map_CAR, mapa_CAR_TAU)
GIII_map_CAR<-rbind(GIII_map_CAR, mapa_CAR_GUA)
```

```{r, "grupo 4 (Buri, Capão Bonito, Ribeirão Grande)"}
GIV_map_uso<-rbind(mapa_uso_BUR, mapa_uso_CAB)
GIV_map_uso<-rbind(GIV_map_uso, mapa_uso_RIG)

GIV_map_mda<-rbind(mapa_mda_BUR, mapa_mda_CAB)
GIV_map_mda<-GIV_map_mda[, -10, drop=FALSE]
GIV_map_mda<-rbind(GIV_map_mda, mapa_mda_RIG)

GIV_map_nas<-rbind(mapa_nas_BUR, mapa_nas_CAB)
GIV_map_nas<-rbind(GIV_map_nas, mapa_nas_RIG)

GIV_map_rms<-rbind(mapa_rms_BUR, mapa_rms_CAB)
GIV_map_rms<-rbind(GIV_map_rms, mapa_rms_RIG)

GIV_map_rmd<-rbind(mapa_rmd_BUR, mapa_rmd_CAB)
GIV_map_rmd<-rbind(GIV_map_rmd, mapa_rmd_RIG)

GIV_map_CAR<-rbind(mapa_CAR_BUR, mapa_CAR_CAB)
GIV_map_CAR<-rbind(GIV_map_CAR, mapa_CAR_RIG)
```

```{r, "Salvando os shp"}
dir.create("./DATA_USE/group_analysis")

writeOGR(GI_map_CAR, dsn = "./DATA_USE/group_analysis", layer = "GI_map_CAR", driver = "ESRI Shapefile")
writeOGR(GI_map_mda, dsn = "./DATA_USE/group_analysis", layer = "GI_map_mda", driver = "ESRI Shapefile")
writeOGR(GI_map_nas, dsn = "./DATA_USE/group_analysis", layer = "GI_map_nas", driver = "ESRI Shapefile")
writeOGR(GI_map_rmd, dsn = "./DATA_USE/group_analysis", layer = "GI_map_rmd", driver = "ESRI Shapefile")
writeOGR(GI_map_rms, dsn = "./DATA_USE/group_analysis", layer = "GI_map_rms", driver = "ESRI Shapefile")
writeOGR(GI_map_uso, dsn = "./DATA_USE/group_analysis", layer = "GI_map_uso", driver = "ESRI Shapefile")

writeOGR(GII_map_CAR, dsn = "./DATA_USE/group_analysis", layer = "GII_map_CAR", driver = "ESRI Shapefile")
writeOGR(GII_map_mda, dsn = "./DATA_USE/group_analysis", layer = "GII_map_mda", driver = "ESRI Shapefile")
writeOGR(GII_map_nas, dsn = "./DATA_USE/group_analysis", layer = "GII_map_nas", driver = "ESRI Shapefile")
writeOGR(GII_map_rmd, dsn = "./DATA_USE/group_analysis", layer = "GII_map_rmd", driver = "ESRI Shapefile")
writeOGR(GII_map_rms, dsn = "./DATA_USE/group_analysis", layer = "GII_map_rms", driver = "ESRI Shapefile")
writeOGR(GII_map_uso, dsn = "./DATA_USE/group_analysis", layer = "GII_map_uso", driver = "ESRI Shapefile")

writeOGR(GIII_map_CAR, dsn = "./DATA_USE/group_analysis", layer = "GIII_map_CAR", driver = "ESRI Shapefile")
writeOGR(GIII_map_mda, dsn = "./DATA_USE/group_analysis", layer = "GIII_map_mda", driver = "ESRI Shapefile")
writeOGR(GIII_map_nas, dsn = "./DATA_USE/group_analysis", layer = "GIII_map_nas", driver = "ESRI Shapefile")
writeOGR(GIII_map_rmd, dsn = "./DATA_USE/group_analysis", layer = "GIII_map_rmd", driver = "ESRI Shapefile")
writeOGR(GIII_map_rms, dsn = "./DATA_USE/group_analysis", layer = "GIII_map_rms", driver = "ESRI Shapefile")
writeOGR(GIII_map_uso, dsn = "./DATA_USE/group_analysis", layer = "GIII_map_uso", driver = "ESRI Shapefile")

writeOGR(GIV_map_CAR, dsn = "./DATA_USE/group_analysis", layer = "GIV_map_CAR", driver = "ESRI Shapefile")
writeOGR(GIV_map_mda, dsn = "./DATA_USE/group_analysis", layer = "GIV_map_mda", driver = "ESRI Shapefile")
writeOGR(GIV_map_nas, dsn = "./DATA_USE/group_analysis", layer = "GIV_map_nas", driver = "ESRI Shapefile")
writeOGR(GIV_map_rmd, dsn = "./DATA_USE/group_analysis", layer = "GIV_map_rmd", driver = "ESRI Shapefile")
writeOGR(GIV_map_rms, dsn = "./DATA_USE/group_analysis", layer = "GIV_map_rms", driver = "ESRI Shapefile")
writeOGR(GIV_map_uso, dsn = "./DATA_USE/group_analysis", layer = "GIV_map_uso", driver = "ESRI Shapefile")
```

